let data = [

    {
        "fullName": "Mika Arai",
        "email": "mattanaka90@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/mika-arai-pmp-leed-8641b067/",
        "company": "N/A",
        "portfolio": "https://mikaarai.com",
        "hobby": "Speakeasy & food",
        openToChat: true,
    },
    {
        "fullName": "Inji Mammadli",
        "email": "mammadlinji@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/inji-mammadli-3b7b71168/",
        "company": "N/A",
        "portfolio": "https://injimammadli.com/portfolio",
        "hobby": "Gaming"
    },
    {
        "fullName": "Devansh Khajanchi",
        "email": "devanshkh@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "www.linkedin.com/in/devanshkh",
        "company": "",
        "portfolio": "https://www.devanshkhajanchi.com/",
        "hobby": "Specialty Coffee",
        openToChat: true,
    },
    {
        "fullName": "Iris Chang",
        "email": "chang.iris96@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/iirischang",
        "company": "N/A",
        "portfolio": "",
        "hobby": "swimming, photography"
    },
    {
        "fullName": "Bhakti Garach",
        "email": "bhaktigarach93@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "www.linkedin.com/in/bhaktigarach",
        "company": "",
        "portfolio": "https://bhaktigarach.com/",
        "hobby": "Cooking, Hiking, Travel",
        openToChat: true,
    },
    {
        "fullName": "Jaehyun Ahn (Irene)",
        "email": "irene3448@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/irene-jh-ahn",
        "company": "N/A",
        "portfolio": "",
        "hobby": "Going to see galleries, Walking around the city, Going to a bookstore"
    },
    {
        "fullName": "Nadia Batchelor",
        "email": "batcn896@newschool.edu",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/nadiabatchelor/",
        "company": "SiteBolts",
        "portfolio": "https://nadabdesigns.com/",
        "hobby": "Photography and 3D Design"
    },
    {
        "fullName": "Ziwei Xing",
        "email": "xingziwei14@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "www.linkedin.com/in/ziwei-xing",
        "company": "N/A",
        "portfolio": "https://ziweixing97.github.io/Portfolio/index.html",
        "hobby": "Listen to music, watch drama TV show, play game"
    },
    {
        "fullName": "Nattakitta Chuasiriphattana",
        "email": "nattakitta.chuasiriphattana@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/nattakitta-chuasiriphattana",
        "company": "N/A",
        "portfolio": "https://opalnattakitta.framer.website",
        "hobby": "Cooking",
        openToChat: true,
    },
    {
        "fullName": "Amy Lewis",
        "email": "ae.lewis15@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/amy-lewis15/",
        "company": "N/A",
        "portfolio": "https://www.amy-lewis.com/",
        "hobby": "Running/Soccer"
    },
    {
        "fullName": "Joshua Estrella",
        "email": "joshuaestrella@me.com",
        "program": "CD",
        "degree": "Bachelor",
        "role": "Associate Design Director",
        "graduated": "Earlier than 2018",
        "linkedin": "https://linkedin.com/in/joshuaestrella",
        "company": "Instrument",
        "portfolio": "",
        "hobby": "Being a silly goose"
    },
    {
        "fullName": "Ishani Koul",
        "email": "ishakoul1098@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/ishani-koul/",
        "company": "N/A",
        "portfolio": "https://ishanikoul.framer.website/",
        "hobby": "Cooking + Eating, Hiking"
    },
    {
        "fullName": "Jonathan Chiang",
        "email": "jonathanchiang7@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/jmchiang5/",
        "company": "N/A",
        "portfolio": "https://jonathanchiang.com/",
        "hobby": "Badminton, Pickleball, Tennis, Dogs"
    },
    {
        "fullName": "Vy Mai (Vee)",
        "email": "Vee.t.mai@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/veemai",
        "company": "N/A",
        "portfolio": "https://Vee-mai.com",
        "hobby": "Cooking, Watching Kdrama, Gym"
    },
    {
        "fullName": "Yuting Zhuang",
        "email": "zhuangyt528@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/yuting-zhuang/",
        "company": "N/A",
        "portfolio": "https://www.yutingzhuang.com/",
        "hobby": "Dancing!"
    },
    {
        "fullName": "Rice Gallardo",
        "email": "raizzart@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "linkedin.com/in/rice-gallardo",
        "company": "N/A",
        "portfolio": "https://ricegallardo.xyz",
        "hobby": "risograph printing, drawing, playing video games, watching movies"
    },
    {
        "fullName": "Tawny Shu",
        "email": "tawny.shu@gmail.com",
        "program": "PD",
        "degree": "Bachelor",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "http://www.linkedin.com/in/tawny-shu-a4233b269",
        "company": "N/A",
        "portfolio": "https://tawnyshu.com",
        "hobby": "Knitting, crochet, sewing. Fiber arts :) check out my Instagram: @wontawn.crochets"
    },
    {
        "fullName": "Mark Huang",
        "email": "Markhuangdesign@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Product designer",
        "graduated": "2022",
        "linkedin": "https://www.linkedin.com/in/thismark?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
        "company": "Meta",
        "portfolio": "",
        "hobby": "Cats, cars and coffee"
    },
    {
        "fullName": "Hamza Iqbal",
        "email": "iqbah960@newschool.edu",
        "program": "CD",
        "degree": "Master's",
        "role": "Product designer",
        "graduated": "2023",
        "linkedin": "https://www.linkedin.com/in/hamzaiqbaldesign",
        "company": "Nappr.io",
        "portfolio": "https://Hamzaiqbal.com",
        "hobby": "Park Slope Food Coop for fun, friends, groceries, everything"
    },
    {
        "fullName": "Nattakitta Chuasiriphattana",
        "email": "nattakitta.chuasiriphattana@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/nattakitta-chuasiriphattana",
        "company": "",
        "portfolio": "https://opalnattakitta.framer.website/",
        "hobby": "Cooking!"
    },
    {
        "fullName": "Isaiah Minor",
        "email": "isaiah.minor@gmail.com",
        "program": "SD",
        "degree": "Bachelor",
        "role": "Senior Product Manager, Crypto Payments",
        "graduated": "2021",
        "linkedin": "https://www.linkedin.com/in/isaiahminor/",
        "company": "Visa Inc.",
        "portfolio": "N/A",
        "hobby": "Exercising, cycling, walking and discovering novel experiences, and trying different types of food."
    },
    {
        "fullName": "Yeo-Kyeong Chung",
        "email": "chuny621@newschool.edu",
        "program": "SD",
        "degree": "Master's",
        "role": "Product Designer",
        "graduated": "2022",
        "linkedin": "https://www.linkedin.com/in/yeo-kyeong-chung/",
        "company": "S&P Global",
        "portfolio": "",
        "hobby": "Dancing, cooking, art stuff(drawing, painting)",
        openToChat: true,
    },
    {
        "fullName": "Yash Sonwaney",
        "email": "yash.sonwaney@newschool.edu",
        "program": "SD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/yashsonwaney",
        "company": "",
        "portfolio": "",
        "hobby": "",
        openToChat: true,
    },
    {
        "fullName": "Carlos Salom",
        "email": "caposalom@gmail.com",
        "program": "SD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/carlossalom/",
        "company": "N/A",
        "portfolio": "",
        "hobby": "Soccer, cooking, writing, live music, running."
    },
    {
        "fullName": "Seth Lukin",
        "email": "hello@sethlukin.com",
        "program": "DT",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/sethlukin/",
        "company": "n/a",
        "portfolio": "https://sethlukin.com/",
        "hobby": "",
        openToChat: true,
    },
    {
        "fullName": "Andre Magracia",
        "email": "andre.magracia@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Product Designer",
        "graduated": "2023",
        "linkedin": "https://www.linkedin.com/in/andremagracia/",
        "company": "JUICE Creative group",
        "portfolio": "https://www.andremagracia.com/",
        "hobby": "Basketball, Formula One, Sneakers, Airplanes, and watches",
        openToChat: true,
    },
    {
        "fullName": "Giordana Pulpo",
        "email": "Rg.pulpo@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Co-founder and Head of Design",
        "graduated": "2022",
        "linkedin": "https://www.linkedin.com/in/giordana-pulpo",
        "company": "Abstractive Health",
        "portfolio": "https://GiordanaPulpo.com",
        "hobby": "Travelling, try new restaurants, hiking, photography, reading",
        openToChat: true,
    },
    {
        "fullName": "Yuri Kawada",
        "email": "yurikawada1@gmail.com",
        "program": "CD",
        "degree": "Bachelor",
        "role": "",
        "graduated": "2019",
        "linkedin": "",
        "company": "N/A",
        "portfolio": "",
        "hobby": ""
    },
    {
        "fullName": "Jenny Yen",
        "email": "jenny61033321@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "linkedin.com/in/jenny-yen-99648820b",
        "company": "N/A",
        "portfolio": "https://jennyenn.com",
        "hobby": "Making coffee and matcha, taking a random walk"
    },
    {
        "fullName": "Shambhavi Varma",
        "email": "varms486@newschool.edu",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/shambhavivarma08/",
        "company": "",
        "portfolio": "https://shamv.framer.website/",
        "hobby": "Sketching, critiquing music and watching movies"
    },
    {
        "fullName": "Emma de Suyrot",
        "email": "emmasuyrot@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/emmadesuyrot/",
        "company": "N/A",
        "portfolio": "https://readymag.website/5250755",
        "hobby": "Padel Tennis, Running, Football (Soccer), F1, Illustrating"
    },
    {
        "fullName": "Sachi Mavinkurve",
        "email": "sachi.mavinkurve@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Freelance/ Self employed",
        "graduated": "2024",
        "linkedin": "https://www.linkedin.com/in/sachi-mavinkurve-5aab41158/",
        "company": "",
        "portfolio": "https://mavinkurve.work/",
        "hobby": "reading and writing",
        openToChat: true,
    },
    {
        "fullName": "Jolyn Tran",
        "email": "tranjolyn@gmail.com",
        "program": "CD",
        "degree": "Master's",
        "role": "Students",
        "graduated": "2025",
        "linkedin": "https://www.linkedin.com/in/jolyntran/",
        "company": "N/A",
        "portfolio": "https://jolyntran.com/",
        "hobby": "Matcha, baking, playing cozy games, ceramics"
    },
    {
        "fullName": "Simran Kaur Pabla",
        "email": "pablasimran7@gmail.com",
        "program": "SD",
        "degree": "Bachelor",
        "role": "Manager, GTM Strategy",
        "graduated": "Earlier than 2018",
        "linkedin": "https://www.linkedin.com/in/simrankpabla/",
        "company": "American Express",
        "portfolio": "",
        "hobby": "legos, reading, working out, cooking",
        openToChat: true,
    },
    {
        "fullName": "Jayna Choksi",
        "email": "jayna0709@gmail.com",
        "program": "CD",
        "degree": "Bachelor",
        "role": "Parsons tutor",
        "graduated": "2025",
        "linkedin": "www.linkedin.com/in/jaynachoksi",
        "company": "",
        "portfolio": "https://jaynachoksi.com",
        "hobby": "Cooking and Football!",
        openToChat: true,
    }
];
   