let data = [
	{
	  "Timestamp": "3/26/2025 11:42:28",
	  "What is your full name?": "Mika Arai",
	  "What is your email address? (it should work after graduation)": "mattanaka90@gmail.com",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "Students",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "https://www.linkedin.com/in/mika-arai-pmp-leed-8641b067/",
	  "Where do you work at? (Write N/A if not applicable)": "N/A",
	  "What is your role? (Ex. product designer or N/A)": "",
	  "Portfolio": "mikaarai.com",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "Speakeasy & food",
	  "Upload your profile picture (Max 5MB)": "https://drive.google.com/open?id=1M9BfLGPwTxBhRaa-pRvg5jTfCDD6Q-1A"
	},
	{
	  "Timestamp": "3/26/2025 12:44:31",
	  "What is your full name?": "Devansh sample data",
	  "What is your email address? (it should work after graduation)": "devanshkh@gmail.com",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "Students, Faculty",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "link",
	  "Where do you work at? (Write N/A if not applicable)": "link",
	  "What is your role? (Ex. product designer or N/A)": "UIUX designer",
	  "Portfolio": "sksh",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "jghkj",
	  "Upload your profile picture (Max 5MB)": ""
	},
	{
	  "Timestamp": "3/26/2025 13:10:12",
	  "What is your full name?": "Inji Mammadli",
	  "What is your email address? (it should work after graduation)": "mammadlinji@gmail.com",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "https://www.linkedin.com/in/inji-mammadli-3b7b71168/",
	  "Where do you work at? (Write N/A if not applicable)": "N/A",
	  "What is your role? (Ex. product designer or N/A)": "UX Designer",
	  "Portfolio": "https://injimammadli.com/portfolio",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "Gaming",
	  "Upload your profile picture (Max 5MB)": ""
	},
	{
	  "Timestamp": "3/26/2025 13:19:09",
	  "What is your full name?": "Devansh Khajanchi",
	  "What is your email address? (it should work after graduation)": "devanshkh@gmail.com",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "www.linkedin.com/in/devanshkh",
	  "Where do you work at? (Write N/A if not applicable)": "",
	  "What is your role? (Ex. product designer or N/A)": "",
	  "Portfolio": "https://www.devanshkhajanchi.com/",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "Specialty Coffee",
	  "Upload your profile picture (Max 5MB)": ""
	},
	{
	  "Timestamp": "3/26/2025 13:20:27",
	  "What is your full name?": "Iris Chang",
	  "What is your email address? (it should work after graduation)": "chang.iris96@gmail.com",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "https://www.linkedin.com/in/iirischang",
	  "Where do you work at? (Write N/A if not applicable)": "N/A",
	  "What is your role? (Ex. product designer or N/A)": "N/A",
	  "Portfolio": "",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "swimming, photography",
	  "Upload your profile picture (Max 5MB)": ""
	},
	{
	  "Timestamp": "3/26/2025 13:23:17",
	  "What is your full name?": "Bhakti Garach",
	  "What is your email address? (it should work after graduation)": "bhaktigarach93@gmail.com",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "www.linkedin.com/in/bhaktigarach",
	  "Where do you work at? (Write N/A if not applicable)": "",
	  "What is your role? (Ex. product designer or N/A)": "Brand/Product Designer",
	  "Portfolio": "https://bhaktigarach.com/",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "Cooking, Hiking, Travel",
	  "Upload your profile picture (Max 5MB)": ""
	},
	{
	  "Timestamp": "3/26/2025 13:25:28",
	  "What is your full name?": "Jaehyun Ahn (Irene)",
	  "What is your email address? (it should work after graduation)": "irene3448@gmail.com",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "https://www.linkedin.com/in/irene-jh-ahn",
	  "Where do you work at? (Write N/A if not applicable)": "N/A",
	  "What is your role? (Ex. product designer or N/A)": "N/A",
	  "Portfolio": "",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "Going to see galleries, Walking around the city, Going to a bookstore",
	  "Upload your profile picture (Max 5MB)": ""
	},
	{
	  "Timestamp": "3/26/2025 13:27:31",
	  "What is your full name?": "Emma de Suyrot",
	  "What is your email address? (it should work after graduation)": "emmasuyrot@gmail.com",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "https://www.linkedin.com/in/emmadesuyrot/",
	  "Where do you work at? (Write N/A if not applicable)": "N/A",
	  "What is your role? (Ex. product designer or N/A)": "Product Designer - UX/UI Design",
	  "Portfolio": "https://readymag.website/5250755",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "Padel Tennis, Footy (Soccer), Doodling, Crochet, Running",
	  "Upload your profile picture (Max 5MB)": ""
	},
	{
	  "Timestamp": "3/26/2025 13:28:52",
	  "What is your full name?": "Nadia Batchelor",
	  "What is your email address? (it should work after graduation)": "batcn896@newschool.edu",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "https://www.linkedin.com/in/nadiabatchelor/",
	  "Where do you work at? (Write N/A if not applicable)": "SiteBolts",
	  "What is your role? (Ex. product designer or N/A)": "UX/UI Designer",
	  "Portfolio": "https://nadabdesigns.com/",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "Photography and 3D Design",
	  "Upload your profile picture (Max 5MB)": ""
	},
	{
	  "Timestamp": "3/26/2025 13:31:10",
	  "What is your full name?": "Ziwei Xing",
	  "What is your email address? (it should work after graduation)": "xingziwei14@gmail.com",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "www.linkedin.com/in/ziwei-xing",
	  "Where do you work at? (Write N/A if not applicable)": "N/A",
	  "What is your role? (Ex. product designer or N/A)": "N/A",
	  "Portfolio": "https://ziweixing97.github.io/Portfolio/index.html",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "Listen to music, watch drama TV show, play game",
	  "Upload your profile picture (Max 5MB)": ""
	},
	{
	  "Timestamp": "3/26/2025 13:34:25",
	  "What is your full name?": "Jenny Yen",
	  "What is your email address? (it should work after graduation)": "jenny61033321@gmail.com",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "https://www.linkedin.com/in/jenny-yen-99648820b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
	  "Where do you work at? (Write N/A if not applicable)": "N/A",
	  "What is your role? (Ex. product designer or N/A)": "N/A",
	  "Portfolio": "https://jennyyen.framer.website/ (haven’t finished yet lol)",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "Making matcha and coffee, random walk in the park",
	  "Upload your profile picture (Max 5MB)": ""
	},
	{
	  "Timestamp": "3/26/2025 14:04:59",
	  "What is your full name?": "Nattakitta Chuasiriphattana",
	  "What is your email address? (it should work after graduation)": "nattakitta.chuasiriphattana@gmail.com",
	  "What is your program?": "CD",
	  "What’s your degree level?": "Master's",
	  "What is/was your role at Parsons?": "",
	  "What is your graduation year?": 2025,
	  "What is your LinkedIn link?": "https://www.linkedin.com/in/nattakitta-chuasiriphattana",
	  "Where do you work at? (Write N/A if not applicable)": "N/A",
	  "What is your role? (Ex. product designer or N/A)": "N/A",
	  "Portfolio": "opalnattakitta.framer.website",
	  "What is your hobby or interest outside work? (Ex. Climbing, photography, cooking, etc.)": "Cooking😋",
	  "Upload your profile picture (Max 5MB)": ""
	}
  ]